apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
  namespace: nexus-dev
spec:
  replicas: 1  # Use 1 for stateful apps unless clustering is configured
  selector:
    matchLabels:
      app: nexus-server
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          resources:
            limits:
              memory: "4Gi"
              cpu: "1000m"
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-data
              mountPath: /nexus-data
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-pvc  # Use a PersistentVolumeClaim for data persistence

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: nexus-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Adjust storage based on your needs

---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus-dev
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8081'
spec:
  selector: 
    app: nexus-server
  type: NodePort  # Or use LoadBalancer if external access is needed
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30008